pipeline {
    agent any
    environment {
        AWS_ACCESS_KEY_ID     = 'tFBWX7SpZ3q0Y1cVNAfWK'
        AWS_SECRET_ACCESS_KEY = '37DgsQsFRgBOOSKzgaC88HEBuaSipILCDepP8fiM'
    }
    stages {
        stage('init') {
            agent {
                docker {
                    image 'hashicorp/terraform:1.9.8'
                    args '-u 0:0 --entrypoint=""'
                    
 
                }
            }
            steps {
                dir('Lab/proxmox/terraform') {
                    sh '''
                      docker run --rm \
                      -v $(pwd):/workspace \
                      -w /workspace \
                      hashicorp/terraform:1.9.8 init -no-color
                    '''
                }
            }
        } 
    }  
}
