version: '3.1'
services:
  jenkins:
    build:
      context: .
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    networks:
      - docker
    ports:
      - 8080:8080
      - 50000:50000
    tty: true
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro

  dind:
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    image: docker:dind
    privileged: true
    restart: always
    networks:
      docker:
        aliases: 
          - docker
    ports:
      - 2376:2376
    tty: true
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
      - docker-cache:/var/lib/docker

  minio:
     image: quay.io/minio/minio:RELEASE.2025-02-03T21-03-04Z-cpuv1
     
     command:
      - server
      - /data
      - --console-address
      - ":9001"
     ports:
      - 9000:9000
      - 9001:9001
     networks:
      docker:
        aliases: 
          - minio
     volumes:
      - minio_data:/data
     environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=rootroot
      - MINIO_DEFAULT_BUCKETS=root
      - MINIO_LICENSE="accepteyJhbGciOiJFUzM4NCIsInR5cCI6IkpXVCJ9.eyJhaWQiOjAsImNhcCI6MSwiZXhwIjoxLjc5MzU2NDExNTY1MDYxMDkyMmU5LCJmZWF0dXJlcyI6WyJPYmplY3RzIiwiVGFibGVzIl0sImdycCI6MCwiaWF0IjoxLjc4ODM4MDExNTY1MDYxMDkyMmU5LCJpc3MiOiJzdWJuZXRAbWluLmlvIiwibGlkIjoiNzEyOGZiNGItYWRhOS00MTUyLTgwZTgtMDI5NzU0YWQ0ZTBiIiwib3JnIjoiYXV0b25vbW8iLCJwbGFuIjoiRU5URVJQUklTRSIsInByb2R1Y3QiOiJBSVN0b3IiLCJyb3AiOjIsInN1YiI6ImF3c3J1c3NvbWFub0BnbWFpbC5jb20iLCJ0cmlhbCI6dHJ1ZSwidmVyIjoxfQ.A1q5PbmE3fmo1FGi1vfkME1BoX3uNsuHirpdbnrxQF4LXyCDgkWP8Ixq7NSNCRbIpJEXI2O9pNRv5zZ43VTah5MdpFja6c0f_tNK4MaSylKVYXgAG2MBXgy331S75vRo"


networks:
  docker:

volumes:
  docker-cache:
  jenkins-data:
  jenkins-docker-certs:
  minio_data: